global:
  fullNameOverride: plex
controllers:
  plex:
    enabled: true
    type: statefulset
    replicas: 1
    statefulset:
      volumeClaimTemplates:
        - name: config
          accessMode: ReadWriteOnce
          size: 5Gi
          storageClass: longhorn
          globalMounts:
            - path: /config
    pod:
      nodeSelector:
        gpu: "i915"
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 100
        supplementalGroups:
          - 44
        fsGroupChangePolicy: "OnRootMismatch"
    containers:
      app:
        image:
          repository: ghcr.io/onedr0p/plex
          tag: 1.41.3.9314-a0bfb8370
          pullPolicy: IfNotPresent
        env:
          TZ: "America/Denver"
          PLEX_ADVERTISE_URL: "https://plex.carsonanderson.net,https://plex.internal.carsonanderson.net,http://10.192.1.114:32400"
          PLEX_NO_AUTH_NETWORKS: "10.244.0.0/16,10.192.0.0/16"
          PLEX_CLAIM:
            valueFrom:
              secretKeyRef:
                name: plex-secrets
                key: PLEX_CLAIM
        probes:
          liveness: &probes
            enabled: true
            custom: true
            spec:
              httpGet:
                path: /identity
                port: 32400
              initialDelaySeconds: 0
              periodSeconds: 10
              timeoutSeconds: 1
              failureThreshold: 3
          readiness: *probes
          startup:
            enabled: false
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
              - ALL
        resources:
          requests:
            gpu.intel.com/i915: 1
            cpu: 200m
            memory: 1Gi
          limits:
            gpu.intel.com/i915: 1
            memory: 8Gi
service:
  app:
    controller: plex
    type: LoadBalancer
    externalTrafficPolicy: Cluster
    ports:
      http:
        port: 32400
persistence:
  data:
    enabled: true
    type: nfs
    server: "nas.carsonanderson.net"
    path: /volume1/nfs
    globalMounts:
      - path: /data
        readOnly: true
  transcode:
    enabled: true
    type: emptyDir
    globalMounts:
      - path: /transcode
