apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mcp-grafana
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secretsmanager
  target:
    name: mcp-grafana
    creationPolicy: Owner
  data:
  - secretKey: GRAFANA_SERVICE_ACCOUNT_TOKEN
    remoteRef:
      key: 895b1950-3c76-4901-bffc-b4d9003664e2
