---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/compare-options: ServerSideDiff=true
  name: sabnzbd
  namespace: argocd
spec:
  sources:
  - repoURL: ghcr.io
    chart: bjw-s/helm/app-template
    targetRevision: 3.6.1
    helm:
      valuesObject:
        global:
          fullnameOverride: sabnzbd
        defaultPodOptions:
          affinity:
            podAntiAffinity:
              preferredDuringSchedulingIgnoredDuringExecution:
                - weight: 80
                  podAffinityTerm:
                    labelSelector:
                      matchExpressions:
                        - key: app.kubernetes.io/name
                          operator: In
                          values:
                            - plex
                    topologyKey: "kubernetes.io/hostname"

        controllers:
          sabnzbd:
            enabled: true
            type: statefulset
            replicas: 1
            statefulset:
              volumeClaimTemplates:
                - name: config
                  accessMode: ReadWriteOnce
                  size: 500Mi
                  storageClass: longhorn
                  globalMounts:
                    - path: /config
                - name: intermediate
                  accessMode: ReadWriteOnce
                  size: 100Gi
                  storageClass: longhorn
                  globalMounts:
                    - path: /intermediate
            pod:
              securityContext:
                runAsUser: 1000
                runAsGroup: 1000
                fsGroup: 1000
                fsGroupChangePolicy: "OnRootMismatch"
            containers:
              app:
                image:
                  repository: ghcr.io/onedr0p/sabnzbd
                  tag: 4.4.1
                  pullPolicy: IfNotPresent
                env:
                  TZ: "America/Denver"
                  SABNZBD__PORT: 8080
                  SABNZBD__HOST_WHITELIST_ENTRIES: >-
                    sabnzbd,
                    sabnzbd.media,
                    sabnzbd.media.svc,
                    sabnzbd.media.svc.cluster,
                    sabnzbd.carsonanderson.net,
                    sabnzbd.carson.teleport.sh,
                envFrom:
                - secretRef:
                    name: sabnzbd
                probes:
                  liveness: &probes
                    enabled: true
                    custom: true
                    spec:
                      httpGet:
                        path: /api?mode=version
                        port: 8080
                      initialDelaySeconds: 0
                      periodSeconds: 10
                      timeoutSeconds: 1
                      failureThreshold: 3
                  readiness: *probes
                  startup:
                    enabled: false
                securityContext:
                  allowPrivilegeEscalation: false
                  capabilities:
                    drop:
                      - ALL
                resources:
                  requests:
                    cpu: 10m
                    memory: 512Mi
                  limits:
                    memory: 8000Mi
        service:
          app:
            primary: true
            controller: sabnzbd
            ports:
              http:
                port: 8080
        persistence:
          data:
            enabled: true
            type: nfs
            server: "nas.carsonanderson.net"
            path: /volume1/nfs
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
  destination:
    namespace: media
    server: https://kubernetes.default.svc
