---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd
spec:
  project: default
  sources:
  - chart: longhorn
    helm:
      valueFiles:
      - $values/argocd/apps/storage/longhorn-system/values.yaml
    repoURL: https://charts.longhorn.io
    targetRevision: 1.7.2
  - repoURL: 'https://github.com/rcanderson23/homelab2.git'
    targetRevision: main
    ref: values
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
  destination:
    namespace: longhorn-system
    server: https://kubernetes.default.svc
