apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: gha-controller-runners-secret-reader
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: gha-controller-runners-secret-reader
subjects:
- kind: ServiceAccount
  name: actions-runner-system-gha-rs-controller
  namespace: actions-runner-system

roleRef:
  kind: Role #this must be Role or ClusterRole
  name: gha-controller-runners-secret-reader
  apiGroup: rbac.authorization.k8s.io
