apiVersion: v1
kind: Secret
metadata:
  labels:
    argocd.argoproj.io/secret-type: repository
  name: actions-runner-system
  namespace: argocd
stringData:
  url: ghcr.io
  name: actions
  type: helm
  enableOCI: "true"
