{
 "title": "Cilium Metrics",
 "description": "Dashboard for Cilium (https://cilium.io/) metrics",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "pod",
    "query": {
     "query": "label_values(cilium_version, pod)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Errors & Warnings",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "opm" }
   ],
   "targets": [
    {
     "expr": "sum(rate(cilium_errors_warnings_total{k8s_app=\"cilium\", pod=~\"$pod\"}[1m])) by (pod, level, cluster) * 60",
     "legendFormat": "{{level}}  {pod=\"{{pod}}\", cluster=\"{{cluster}}\"}"
    }
   ]
  },
  {
   "title": "CPU Usage per node",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "min(irate(cilium_process_cpu_seconds_total{k8s_app=\"cilium\", pod=~\"$pod\"}[1m])) by (pod, cluster) * 100",
     "legendFormat": "min {pod=\"{{pod}}\", cluster=\"{{cluster}}\"}"
    },
    {
     "expr": "avg(irate(cilium_process_cpu_seconds_total{k8s_app=\"cilium\", pod=~\"$pod\"}[1m])) by (pod, cluster) * 100",
     "legendFormat": "avg {pod=\"{{pod}}\", cluster=\"{{cluster}}\"}"
    },
    {
     "expr": "max(irate(cilium_process_cpu_seconds_total{k8s_app=\"cilium\", pod=~\"$pod\"}[1m])) by (pod, cluster) * 100",
     "legendFormat": "max {pod=\"{{pod}}\", cluster=\"{{cluster}}\"}"
    }
   ]
  },
  { "title": "Generic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Virtual Memory Bytes",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "min(cilium_process_virtual_memory_bytes{k8s_app=\"cilium\", pod=~\"$pod\"}) by (cluster)",
     "legendFormat": "Min Virtual Memory {cluster=\"{{cluster}}\"}"
    },
    {
     "expr": "avg(cilium_process_virtual_memory_bytes{k8s_app=\"cilium\", pod=~\"$pod\"}) by (cluster)",
     "legendFormat": "Average Virtual Memory  {cluster=\"{{cluster}}\"}"
    },
    {
     "expr": "max(cilium_process_virtual_memory_bytes{k8s_app=\"cilium\", pod=~\"$pod\"}) by (cluster)",
     "legendFormat": "Max Virtual Memory  {cluster=\"{{cluster}}\"}"
    }
   ]
  },
  {
   "title": "Resident memory status",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 6 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "avg(cilium_process_resident_memory_bytes{k8s_app=\"cilium\", pod=~\"$pod\"}) by (cluster)",
     "legendFormat": "AVG_resident_memory_bytes  {cluster=\"{{cluster}}\"}"
    },
    {
     "expr": "max(cilium_process_resident_memory_bytes{k8s_app=\"cilium\", pod=~\"$pod\"}) by (cluster)",
     "legendFormat": "MAX_resident_memory_bytes_max  {cluster=\"{{cluster}}\"}"
    },
    {
     "expr": "min(cilium_process_resident_memory_bytes{k8s_app=\"cilium\", pod=~\"$pod\"}) by (cluster)",
     "legendFormat": "MIN_resident_memory_bytes_min  {cluster=\"{{cluster}}\"}"
    }
   ]
  },
  {
   "title": "Open file descriptors",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(cilium_process_open_fds{k8s_app=\"cilium\", pod=~\"$pod\"}) by (cluster)",
     "legendFormat": "all nodes {cluster=\"{{cluster}}\"}"
    },
    {
     "expr": "min(cilium_process_open_fds{k8s_app=\"cilium\", pod=~\"$pod\"}) by (cluster)",
     "legendFormat": "min/node {cluster=\"{{cluster}}\"}"
    },
    {
     "expr": "avg(cilium_process_open_fds{k8s_app=\"cilium\", pod=~\"$pod\"}) by (cluster)",
     "legendFormat": "avg/node {cluster=\"{{cluster}}\"}"
    },
    {
     "expr": "max(cilium_process_open_fds{k8s_app=\"cilium\", pod=~\"$pod\"})",
     "legendFormat": "max/node"
    }
   ]
  },
  {
   "title": "System-wide BPF memory usage",
   "type": "graph",
   "description": "BPF memory usage in the entire system including components not managed by Cilium.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "avg(cilium_bpf_maps_virtual_memory_max_bytes{k8s_app=\"cilium\", pod=~\"$pod\"} + cilium_bpf_progs_virtual_memory_max_bytes{k8s_app=\"cilium\", pod=~\"$pod\"}) by (cluster)",
     "legendFormat": "AVG_bpf_memory_bytes_avg  {cluster=\"{{cluster}}\"}"
    },
    {
     "expr": "max(cilium_bpf_maps_virtual_memory_max_bytes{k8s_app=\"cilium\", pod=~\"$pod\"} + cilium_bpf_progs_virtual_memory_max_bytes{k8s_app=\"cilium\", pod=~\"$pod\"}) by (cluster)",
     "legendFormat": "MAX_bpf_memory_bytes_max  {cluster=\"{{cluster}}\"}"
    },
    {
     "expr": "min(cilium_bpf_maps_virtual_memory_max_bytes{k8s_app=\"cilium\", pod=~\"$pod\"} + cilium_bpf_progs_virtual_memory_max_bytes{k8s_app=\"cilium\", pod=~\"$pod\"}) by (cluster)",
     "legendFormat": "MIN_bpf_memory_bytes_min  {cluster=\"{{cluster}}\"}"
    }
   ]
  },
  {
   "title": "BPF map pressure",
   "type": "graph",
   "description": "Fill percentage of BPF maps, tagged by map name",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "cilium_bpf_map_pressure{k8s_app=\"cilium\", pod=~\"$pod\"}"
    }
   ]
  },
  { "title": "API", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "API call latency (average node)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(rate(cilium_agent_api_process_time_seconds_sum{k8s_app=\"cilium\", pod=~\"$pod\"}[1m])/rate(cilium_agent_api_process_time_seconds_count{k8s_app=\"cilium\", pod=~\"$pod\"}[1m])) by (pod, method, path, cluster)",
     "legendFormat": "{{method}} {{path}}  {pod=\"{{pod}}\", cluster=\"{{cluster}}\"}"
    }
   ]
  },
  {
   "title": "API call latency (max node)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "max(rate(cilium_agent_api_process_time_seconds_sum{k8s_app=\"cilium\", pod=~\"$pod\"}[1m])/rate(cilium_agent_api_process_time_seconds_count{k8s_app=\"cilium\", pod=~\"$pod\"}[1m])) by (pod, method, path, cluster)",
     "legendFormat": "{{method}} {{path}} {pod=\"{{pod}}\", cluster=\"{{cluster}}\"}"
    }
   ]
  },
  {
   "title": "# API calls (average node)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "avg(rate(cilium_agent_api_process_time_seconds_count{k8s_app=\"cilium\", pod=~\"$pod\"}[1m])) by (pod, method, path, cluster)",
     "legendFormat": "{{method}} {{path}}  {pod=\"{{pod}}\", cluster=\"{{cluster}}\"}"
    }
   ]
  },
  {
   "title": "# API calls (max node)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "max(rate(cilium_agent_api_process_time_seconds_count{k8s_app=\"cilium\", pod=~\"$pod\"}[1m])) by (pod, method, path, cluster)",
     "legendFormat": "{{method}} {{path}} {pod=\"{{pod}}\", cluster=\"{{cluster}}\"}"
    }
   ]
  },
  {
   "title": "API return codes (average node)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "avg(rate(cilium_agent_api_process_time_seconds_count{k8s_app=\"cilium\", pod=~\"$pod\"}[1m])) by (pod, method, path, return_code, cluster)",
     "legendFormat": "{{return_code}} ({{method}} {{path}}) {pod=\"{{pod}}\", cluster=\"{{cluster}}\"}"
    }
   ]
  },
  {
   "title": "API return codes (sum all nodes)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 30 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(cilium_agent_api_process_time_seconds_count{k8s_app=\"cilium\", pod=~\"$pod\"}[1m])) by (pod, method, path, return_code, cluster)",
     "legendFormat": "{{return_code}} ({{method}} {{path}}) {pod=\"{{pod}}\", cluster=\"{{cluster}}\"}"
    }
   ]
  },
  { "title": "Cilium", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  { "title": "BPF", "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } },
  {
   "title": "# system calls (average node)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "avg(rate(cilium_bpf_syscall_duration_seconds_count{k8s_app=\"cilium\", pod=~\"$pod\"}[1m])) by (pod, operation, cluster)",
     "legendFormat": "{{operation}} {pod=\"{{pod}}\", cluster=\"{{cluster}}\"}"
    }
   ]
  },
  {
   "title": "# system calls (max node)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "max(rate(cilium_bpf_syscall_duration_seconds_count{k8s_app=\"cilium\", pod=~\"$pod\"}[1m])) by (pod, operation, cluster)",
     "legendFormat": "{{operation}} {pod=\"{{pod}}\", cluster=\"{{cluster}}\"}"
    }
   ]
  },
  {
   "title": "system call latency (avg node)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(rate(cilium_bpf_syscall_duration_seconds_sum{k8s_app=\"cilium\", pod=~\"$pod\"}[1m])/ rate(cilium_bpf_syscall_duration_seconds_count{k8s_app=\"cilium\", pod=~\"$pod\"}[1m])) by (pod, operation, cluster)",
     "legendFormat": "{{operation}} {pod=\"{{pod}}\", cluster=\"{{cluster}}\"}"
    }
   ]
  },
  {
   "title": "system call latency (max node)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 46 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "max(rate(cilium_bpf_syscall_duration_seconds_sum{k8s_app=\"cilium\", pod=~\"$pod\"}[1m])/ rate(cilium_bpf_syscall_duration_seconds_count{k8s_app=\"cilium\", pod=~\"$pod\"}[1m])) by (pod, operation, cluster)",
     "legendFormat": "{{operation}} {pod=\"{{pod}}\", cluster=\"{{cluster}}\"}"
    }
   ]
  },
  {
   "title": "map ops (average node)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 52 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "topk(5, avg(rate(cilium_bpf_map_ops_total{k8s_app=\"cilium\", pod=~\"$pod\"}[5m])) by (pod, map_name, operation, cluster))",
     "legendFormat": "{{map_name}} {{operation}} {pod=\"{{pod}}\", cluster=\"{{cluster}}\"}"
    }
   ]
  },
  {
   "title": "map ops (max node)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 52 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "topk(5, max(rate(cilium_bpf_map_ops_total{k8s_app=\"cilium\", pod=~\"$pod\"}[5m])) by (pod, map_name, operation, cluster))",
     "legendFormat": "{{map_name}} {{operation}} {pod=\"{{pod}}\", cluster=\"{{cluster}}\"}"
    }
   ]
  },
  {
   "title": "map ops (sum failures)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 52 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(cilium_bpf_map_ops_total{k8s_app=\"cilium\",outcome=\"fail\", pod=~\"$pod\"}[5m])) by (pod, map_name, operation, cluster)",
     "legendFormat": "{{map_name}} {{operation}} {pod=\"{{pod}}\", cluster=\"{{cluster}}\"}"
    }
   ]
  },
  { "title": "kvstore", "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 58 } },
  {
   "title": "latency (average node)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 59 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "topk(5, avg(rate(cilium_kvstore_operations_duration_seconds_sum{pod=~\"$pod\"}[1m])) by (pod, action, scope, cluster) / avg(rate(cilium_kvstore_operations_duration_seconds_count{pod=~\"$pod\"}[1m])) by (pod, action, scope, cluster))",
     "legendFormat": "{{action}} {{scope}} {pod=\"{{pod}}\", cluster=\"{{cluster}}\"}"
    }
   ]
  },
  {
   "title": "latency (max node)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 59 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "topk(5, max(rate(cilium_kvstore_operations_duration_seconds_sum{pod=~\"$pod\"}[1m])) by (pod, action, scope, cluster) / avg(rate(cilium_kvstore_operations_duration_seconds_count{pod=~\"$pod\"}[1m])) by (pod, action, scope, cluster))",
     "legendFormat": "{{action}} {{scope}} {pod=\"{{pod}}\", cluster=\"{{cluster}}\"}"
    }
   ]
  },
  {
   "title": "Events received (average node)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 64 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "avg(rate(cilium_kvstore_events_queue_seconds_count{pod=~\"$pod\"}[1m])) by (pod, scope, action, cluster)",
     "legendFormat": "{{action}} {{scope}} {pod=\"{{pod}}\", cluster=\"{{cluster}}\"}"
    }
   ]
  },
  { "title": "Cilium network information", "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 70 } },
  {
   "title": "Forwarded Packets",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 71 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(cilium_forward_count_total{k8s_app=\"cilium\", pod=~\"$pod\"}[1m])) by (pod, direction, cluster)",
     "legendFormat": "{{direction}} {pod=\"{{pod}}\", cluster=\"{{cluster}}\"}"
    }
   ]
  },
  {
   "title": "Forwarded Traffic",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 71 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(cilium_forward_bytes_total{k8s_app=\"cilium\", pod=~\"$pod\"}[1m])) by (pod, direction, cluster) * 8",
     "legendFormat": "{{direction}} {pod=\"{{pod}}\", cluster=\"{{cluster}}\"}"
    }
   ]
  },
  {
   "title": "IPv4 Conntrack TCP",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 77 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "min(cilium_datapath_conntrack_gc_entries{k8s_app=\"cilium\", status=\"alive\", family=\"ipv4\", protocol=\"TCP\", pod=~\"$pod\"}) by (family,status, cluster)",
     "legendFormat": "min {cluster=\"{{cluster}}\"}"
    },
    {
     "expr": "avg(cilium_datapath_conntrack_gc_entries{k8s_app=\"cilium\", status=\"alive\", family=\"ipv4\", protocol=\"TCP\", pod=~\"$pod\"}) by (family,status, cluster)",
     "legendFormat": "avg {cluster=\"{{cluster}}\"}"
    },
    {
     "expr": "max(cilium_datapath_conntrack_gc_entries{k8s_app=\"cilium\", status=\"alive\", family=\"ipv4\", protocol=\"TCP\", pod=~\"$pod\"}) by (family,status, cluster)",
     "legendFormat": "max {cluster=\"{{cluster}}\"}"
    },
    {
     "expr": "avg(cilium_datapath_conntrack_gc_entries{k8s_app=\"cilium\", status=\"deleted\", family=\"ipv4\", protocol=\"TCP\", pod=~\"$pod\"}) by (family,status, cluster)",
     "legendFormat": "deleted {cluster=\"{{cluster}}\"}"
    },
    {
     "expr": "max(cilium_datapath_conntrack_gc_entries{k8s_app=\"cilium\", status=\"deleted\", family=\"ipv4\", protocol=\"TCP\", pod=~\"$pod\"}) by (family,status, cluster)",
     "legendFormat": "deleted max {cluster=\"{{cluster}}\"}"
    }
   ]
  },
  {
   "title": "IPv6 Conntrack TCP",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 77 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "min(cilium_datapath_conntrack_gc_entries{k8s_app=\"cilium\", status=\"alive\", family=\"ipv6\", protocol=\"TCP\", pod=~\"$pod\"}) by (family,status, cluster)",
     "legendFormat": "min {cluster=\"{{cluster}}\"}"
    },
    {
     "expr": "avg(cilium_datapath_conntrack_gc_entries{k8s_app=\"cilium\", status=\"alive\", family=\"ipv6\", protocol=\"TCP\", pod=~\"$pod\"}) by (family,status, cluster)",
     "legendFormat": "avg {cluster=\"{{cluster}}\"}"
    },
    {
     "expr": "max(cilium_datapath_conntrack_gc_entries{k8s_app=\"cilium\", status=\"alive\", family=\"ipv6\", protocol=\"TCP\", pod=~\"$pod\"}) by (family,status, cluster)",
     "legendFormat": "max {cluster=\"{{cluster}}\"}"
    },
    {
     "expr": "avg(cilium_datapath_conntrack_gc_entries{k8s_app=\"cilium\", status=\"deleted\", family=\"ipv6\", protocol=\"TCP\", pod=~\"$pod\"}) by (family,status, cluster)",
     "legendFormat": "deleted {cluster=\"{{cluster}}\"}"
    },
    {
     "expr": "max(cilium_datapath_conntrack_gc_entries{k8s_app=\"cilium\", status=\"deleted\", family=\"ipv6\", protocol=\"TCP\", pod=~\"$pod\"}) by (family,status, cluster)",
     "legendFormat": "deleted max {cluster=\"{{cluster}}\"}"
    }
   ]
  },
  {
   "title": "IPv4 Conntrack Non-TCP",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 83 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "min(cilium_datapath_conntrack_gc_entries{k8s_app=\"cilium\", status=\"alive\", family=\"ipv4\", protocol=\"non-TCP\", pod=~\"$pod\"}) by (family,status, cluster)",
     "legendFormat": "min {cluster=\"{{cluster}}\"}"
    },
    {
     "expr": "avg(cilium_datapath_conntrack_gc_entries{k8s_app=\"cilium\", status=\"alive\", family=\"ipv4\", protocol=\"non-TCP\", pod=~\"$pod\"}) by (family,status, cluster)",
     "legendFormat": "avg {cluster=\"{{cluster}}\"}"
    },
    {
     "expr": "max(cilium_datapath_conntrack_gc_entries{k8s_app=\"cilium\", status=\"alive\", family=\"ipv4\", protocol=\"non-TCP\", pod=~\"$pod\"}) by (family,status, cluster)",
     "legendFormat": "max {cluster=\"{{cluster}}\"}"
    },
    {
     "expr": "avg(cilium_datapath_conntrack_gc_entries{k8s_app=\"cilium\", status=\"deleted\", family=\"ipv4\", protocol=\"non-TCP\", pod=~\"$pod\"}) by (family,status, cluster)",
     "legendFormat": "deleted {cluster=\"{{cluster}}\"}"
    },
    {
     "expr": "max(cilium_datapath_conntrack_gc_entries{k8s_app=\"cilium\", status=\"deleted\", family=\"ipv4\", protocol=\"non-TCP\", pod=~\"$pod\"}) by (family,status, cluster)",
     "legendFormat": "deleted max {cluster=\"{{cluster}}\"}"
    }
   ]
  },
  {
   "title": "IPv6 Conntrack Non-TCP",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 83 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "min(cilium_datapath_conntrack_gc_entries{k8s_app=\"cilium\", status=\"alive\", family=\"ipv6\", protocol=\"non-TCP\", pod=~\"$pod\"}) by (family,status,cluster)",
     "legendFormat": "min {cluster=\"{{cluster}}\"}"
    },
    {
     "expr": "avg(cilium_datapath_conntrack_gc_entries{k8s_app=\"cilium\", status=\"alive\", family=\"ipv6\", protocol=\"non-TCP\", pod=~\"$pod\"}) by (family,status,cluster)",
     "legendFormat": "avg {cluster=\"{{cluster}}\"}"
    },
    {
     "expr": "max(cilium_datapath_conntrack_gc_entries{k8s_app=\"cilium\", status=\"alive\", family=\"ipv6\", protocol=\"non-TCP\", pod=~\"$pod\"}) by (family,status,cluster)",
     "legendFormat": "max {cluster=\"{{cluster}}\"}"
    },
    {
     "expr": "avg(cilium_datapath_conntrack_gc_entries{k8s_app=\"cilium\", status=\"deleted\", family=\"ipv6\", protocol=\"non-TCP\", pod=~\"$pod\"}) by (family,status,cluster)",
     "legendFormat": "deleted {cluster=\"{{cluster}}\"}"
    },
    {
     "expr": "max(cilium_datapath_conntrack_gc_entries{k8s_app=\"cilium\", status=\"deleted\", family=\"ipv6\", protocol=\"non-TCP\", pod=~\"$pod\"}) by (family,status,cluster)",
     "legendFormat": "deleted max {cluster=\"{{cluster}}\"}"
    }
   ]
  },
  {
   "title": "Allocated Addresses",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 89 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(cilium_ip_addresses{k8s_app=\"cilium\", pod=~\"$pod\"}) by (pod, family, cluster)\n",
     "legendFormat": "{{family}} {pod=\"{{pod}}\", cluster=\"{{cluster}}\"}"
    }
   ]
  },
  {
   "title": "Datapath Conntrack Dump Resets",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 89 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(cilium_datapath_conntrack_dump_resets_total{k8s_app=\"cilium\", pod=~\"$pod\"}) by (pod, area, family, name, cluster)",
     "legendFormat": "{{name}} {{area}} {{family}} {pod=\"{{pod}}\", cluster=\"{{cluster}}\"}"
    }
   ]
  },
  {
   "title": "Service Updates",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 94 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "avg(rate(cilium_services_events_total{k8s_app=\"cilium\", pod=~\"$pod\"}[1m])) by (pod, action, cluster)",
     "legendFormat": "{{action}} {pod=\"{{pod}}\", cluster=\"{{cluster}}\"}"
    }
   ]
  },
  {
   "title": "Connectivity Health",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 94 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(cilium_unreachable_nodes{k8s_app=\"cilium\", pod=~\"$pod\"}) by (pod, cluster)",
     "legendFormat": "unreachable nodes {pod=\"{{pod}}\", cluster=\"{{cluster}}\"}"
    },
    {
     "expr": "sum(cilium_unreachable_health_endpoints{k8s_app=\"cilium\", pod=~\"$pod\"}) by (pod, cluster)",
     "legendFormat": "unreachable health endpoints {pod=\"{{pod}}\", cluster=\"{{cluster}}\"}"
    }
   ]
  },
  {
   "title": "Dropped Egress Packets",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 99 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(cilium_drop_count_total{direction=\"EGRESS\", k8s_app=\"cilium\", pod=~\"$pod\"}[1m])) by (reason, cluster)",
     "legendFormat": "{{reason}} {cluster=\"{{cluster}}\"}"
    }
   ]
  },
  {
   "title": "Node Events",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 99 },
   "yaxes": [
    { "format": "opm" }
   ],
   "targets": [
    {
     "expr": "avg(rate(cilium_nodes_all_events_received_total{k8s_app=\"cilium\", pod=~\"$pod\"}[1m])) by (pod, event_type, source, cluster) * 60",
     "legendFormat": "{{eventType}} {{source}} {pod=\"{{pod}}\", cluster=\"{{cluster}}\"}"
    }
   ]
  },
  {
   "title": "Dropped Egress Traffic",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 104 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(cilium_drop_bytes_total{direction=\"EGRESS\", k8s_app=\"cilium\", pod=~\"$pod\"}[1m])) by (reason, cluster) * 8",
     "legendFormat": "{{reason}} {cluster=\"{{cluster}}\"}"
    }
   ]
  },
  {
   "title": "Nodes",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 104 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(cilium_nodes_all_num{k8s_app=\"cilium\", pod=~\"$pod\"}) by (pod, cluster)",
     "legendFormat": "Average Nodes {pod=\"{{pod}}\", cluster=\"{{cluster}}\"}"
    },
    {
     "expr": "min(cilium_nodes_all_num{k8s_app=\"cilium\", pod=~\"$pod\"}) by (pod, cluster)",
     "legendFormat": "Min Nodes {pod=\"{{pod}}\", cluster=\"{{cluster}}\"}"
    },
    {
     "expr": "max(cilium_nodes_all_num{k8s_app=\"cilium\", pod=~\"$pod\"}) by (pod, cluster)",
     "legendFormat": "Max Nodes {pod=\"{{pod}}\", cluster=\"{{cluster}}\"}"
    }
   ]
  },
  { "title": "Policy", "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 109 } },
  {
   "title": "L7 forwarded request",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 110 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(cilium_policy_l7_denied_total{k8s_app=\"cilium\", pod=~\"$pod\"}[1m])) by (cluster)",
     "legendFormat": "denied {cluster=\"{{cluster}}\"}"
    },
    {
     "expr": "sum(rate(cilium_policy_l7_forwarded_total{k8s_app=\"cilium\", pod=~\"$pod\"}[1m])) by (cluster)",
     "legendFormat": "forwarded {cluster=\"{{cluster}}\"}"
    },
    {
     "expr": "sum(rate(cilium_policy_l7_received_total{k8s_app=\"cilium\", pod=~\"$pod\"}[1m])) by (cluster)",
     "legendFormat": "received {cluster=\"{{cluster}}\"}"
    }
   ]
  },
  {
   "title": "Cilium drops Ingress",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 110 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(cilium_drop_count_total{direction=\"INGRESS\", k8s_app=\"cilium\", pod=~\"$pod\"}[5m])) by (reason, cluster)",
     "legendFormat": "{{reason}} {cluster=\"{{cluster}}\"}"
    }
   ]
  },
  {
   "title": "Proxy response time (Avg)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 115 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(rate(cilium_proxy_upstream_reply_seconds_sum{k8s_app=\"cilium\", pod=~\"$pod\"}[1m])) by (pod, scope, cluster) / sum(rate(cilium_proxy_upstream_reply_seconds_count{k8s_app=\"cilium\", pod=~\"$pod\"}[1m])) by (pod, scope, cluster)",
     "legendFormat": "{{scope}} {pod=\"{{pod}}\", cluster=\"{{cluster}}\"}"
    },
    {
     "expr": "avg(cilium_policy_l7_parse_errors_total{k8s_app=\"cilium\", pod=~\"$pod\"}) by (pod, cluster)",
     "legendFormat": "parse errors {pod=\"{{pod}}\", cluster=\"{{cluster}}\"}"
    }
   ]
  },
  {
   "title": "Dropped Ingress Traffic",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 115 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(cilium_drop_bytes_total{direction=\"INGRESS\", k8s_app=\"cilium\", pod=~\"$pod\"}[1m])) by (reason, cluster) * 8",
     "legendFormat": "{{reason}} {cluster=\"{{cluster}}\"}"
    }
   ]
  },
  {
   "title": "Policy Trigger Duration",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 120 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "min(rate(cilium_triggers_policy_update_call_duration_seconds_sum{k8s_app=\"cilium\", pod=~\"$pod\"}[1m])) by (pod, scope, cluster) / sum(rate(cilium_triggers_policy_update_call_duration_seconds_count{k8s_app=\"cilium\", pod=~\"$pod\"}[1m])) by (pod, scope, cluster)",
     "legendFormat": "min {pod=\"{{pod}}\", cluster=\"{{cluster}}\"}"
    },
    {
     "expr": "avg(rate(cilium_triggers_policy_update_call_duration_seconds_sum{k8s_app=\"cilium\", pod=~\"$pod\"}[1m])) by (pod, scope, cluster) / sum(rate(cilium_triggers_policy_update_call_duration_seconds_count{k8s_app=\"cilium\", pod=~\"$pod\"}[1m])) by (pod, scope, cluster)",
     "legendFormat": "avg {pod=\"{{pod}}\", cluster=\"{{cluster}}\"}"
    },
    {
     "expr": "max(rate(cilium_triggers_policy_update_call_duration_seconds_sum{k8s_app=\"cilium\", pod=~\"$pod\"}[1m])) by (pod, scope, cluster) / sum(rate(cilium_triggers_policy_update_call_duration_seconds_count{k8s_app=\"cilium\", pod=~\"$pod\"}[1m])) by (pod, scope, cluster)",
     "legendFormat": "max {pod=\"{{pod}}\", cluster=\"{{cluster}}\"}"
    }
   ]
  },
  {
   "title": "Proxy response time (Max)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 120 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "max(rate(cilium_proxy_upstream_reply_seconds_sum{k8s_app=\"cilium\", pod=~\"$pod\"}[1m])) by (pod, scope, cluster) / sum(rate(cilium_proxy_upstream_reply_seconds_count{k8s_app=\"cilium\", pod=~\"$pod\"}[1m])) by (pod, scope, cluster)",
     "legendFormat": "Max {{scope}} {pod=\"{{pod}}\", cluster=\"{{cluster}}\"}"
    },
    {
     "expr": "max(rate(cilium_policy_l7_parse_errors_total{k8s_app=\"cilium\", pod=~\"$pod\"}[1m])) by (pod, cluster)",
     "legendFormat": "parse errors {pod=\"{{pod}}\", cluster=\"{{cluster}}\"}"
    }
   ]
  },
  {
   "title": "Endpoints policy enforcement status",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 125 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(cilium_policy_endpoint_enforcement_status{k8s_app=\"cilium\", pod=~\"$pod\"}) by (enforcement, cluster)",
     "legendFormat": "{{enforcement}} {cluster=\"{{cluster}}\"}"
    }
   ]
  },
  {
   "title": "Policy Trigger Runs",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 125 },
   "yaxes": [
    { "format": "opm" }
   ],
   "targets": [
    {
     "expr": "min(rate(cilium_triggers_policy_update_total{k8s_app=\"cilium\", pod=~\"$pod\"}[1m])) by (pod, cluster) * 60",
     "legendFormat": "min trigger {pod=\"{{pod}}\", cluster=\"{{cluster}}\"}"
    },
    {
     "expr": "avg(rate(cilium_triggers_policy_update_total{k8s_app=\"cilium\", pod=~\"$pod\"}[1m])) by (pod, cluster) * 60",
     "legendFormat": "average trigger {pod=\"{{pod}}\", cluster=\"{{cluster}}\"}"
    },
    {
     "expr": "max(rate(cilium_triggers_policy_update_total{k8s_app=\"cilium\", pod=~\"$pod\"}[1m])) by (pod, cluster) * 60",
     "legendFormat": "max trigger {pod=\"{{pod}}\", cluster=\"{{cluster}}\"}"
    },
    {
     "expr": "max(rate(cilium_triggers_policy_update_folds{k8s_app=\"cilium\", pod=~\"$pod\"}[1m])) by (pod, cluster) * 60",
     "legendFormat": "folds {pod=\"{{pod}}\", cluster=\"{{cluster}}\"}"
    }
   ]
  },
  {
   "title": "Proxy Redirects",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 130 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "min(cilium_proxy_redirects{k8s_app=\"cilium\", pod=~\"$pod\"}) by (pod, cluster)",
     "legendFormat": "min {pod=\"{{pod}}\", cluster=\"{{cluster}}\"}"
    },
    {
     "expr": "avg(cilium_proxy_redirects{k8s_app=\"cilium\", pod=~\"$pod\"}) by (pod, cluster)",
     "legendFormat": "avg {pod=\"{{pod}}\", cluster=\"{{cluster}}\"}"
    },
    {
     "expr": "max(cilium_proxy_redirects{k8s_app=\"cilium\", pod=~\"$pod\"}) by (pod, cluster)",
     "legendFormat": "max {pod=\"{{pod}}\", cluster=\"{{cluster}}\"}"
    }
   ]
  },
  {
   "title": "DNS proxy requests",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 130 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "avg(rate(cilium_proxy_upstream_reply_seconds_count{k8s_app=\"cilium\", pod=~\"$pod\"}[1m])) by (pod, scope, cluster)",
     "legendFormat": "{{scope}} {pod=\"{{pod}}\", cluster=\"{{cluster}}\"}"
    }
   ]
  },
  {
   "title": "Policies Per Node",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 135 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "min(cilium_policy{k8s_app=\"cilium\", pod=~\"$pod\"}) by(pod, cluster)",
     "legendFormat": "min {pod=\"{{pod}}\", cluster=\"{{cluster}}\"}"
    },
    {
     "expr": "avg(cilium_policy{k8s_app=\"cilium\", pod=~\"$pod\"}) by(pod, cluster)",
     "legendFormat": "avg {pod=\"{{pod}}\", cluster=\"{{cluster}}\"}"
    },
    {
     "expr": "max(cilium_policy{k8s_app=\"cilium\", pod=~\"$pod\"}) by(pod, cluster)",
     "legendFormat": "max {pod=\"{{pod}}\", cluster=\"{{cluster}}\"}"
    },
    {
     "expr": "sum(cilium_policy_import_errors_total{k8s_app=\"cilium\", pod=~\"$pod\"}) by (pod, cluster)",
     "legendFormat": "policy import errors {pod=\"{{pod}}\", cluster=\"{{cluster}}\"}"
    }
   ]
  },
  {
   "title": "Policy Revision",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 135 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "min(cilium_policy_max_revision{k8s_app=\"cilium\", pod=~\"$pod\"}) by (pod, cluster)",
     "legendFormat": "min {pod=\"{{pod}}\", cluster=\"{{cluster}}\"}"
    },
    {
     "expr": "avg(cilium_policy_max_revision{k8s_app=\"cilium\", pod=~\"$pod\"}) by (pod, cluster)",
     "legendFormat": "avg {pod=\"{{pod}}\", cluster=\"{{cluster}}\"}"
    },
    {
     "expr": "max(cilium_policy_max_revision{k8s_app=\"cilium\", pod=~\"$pod\"}) by (pod, cluster)",
     "legendFormat": "max {pod=\"{{pod}}\", cluster=\"{{cluster}}\"}"
    }
   ]
  },
  { "title": "Endpoints", "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 140 } },
  {
   "title": "Endpoint regeneration time (90th percentile)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 141 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(histogram_quantile(0.90, rate(cilium_endpoint_regeneration_time_stats_seconds_bucket{k8s_app=\"cilium\", scope!=\"total\", pod=~\"$pod\"}[5m]))) by (scope, cluster)",
     "legendFormat": "{{scope}} {cluster=\"{{cluster}}\"}"
    }
   ]
  },
  {
   "title": "Endpoint regeneration time (99th percentile)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 141 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(histogram_quantile(0.99, rate(cilium_endpoint_regeneration_time_stats_seconds_bucket{k8s_app=\"cilium\", scope!=\"total\", pod=~\"$pod\"}[5m]))) by (scope, cluster)",
     "legendFormat": "{{scope}} {cluster=\"{{cluster}}\"}"
    }
   ]
  },
  {
   "title": "Endpoint regenerations",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 150 },
   "yaxes": [
    { "format": "opm" }
   ],
   "targets": [
    {
     "expr": "sum(rate(cilium_endpoint_regenerations_total{k8s_app=\"cilium\", pod=~\"$pod\"}[30s])) by(outcome, cluster)",
     "legendFormat": "{{outcome}} {cluster=\"{{cluster}}\"}"
    }
   ]
  },
  {
   "title": "Cilium endpoint state",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 150 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(cilium_endpoint_state{k8s_app=\"cilium\", pod=~\"$pod\"}) by (endpoint_state, cluster)",
     "legendFormat": "{{endpoint_state}} {cluster=\"{{cluster}}\"}"
    }
   ]
  },
  { "title": "Controllers", "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 155 } },
  {
   "title": "Controllers",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 156 },
   "yaxes": [
    { "format": "opm" }
   ],
   "targets": [
    {
     "expr": "sum(rate(cilium_controllers_runs_total{k8s_app=\"cilium\", pod=~\"$pod\"}[1m])) by (pod, cluster)",
     "legendFormat": "Runs {pod=\"{{pod}}\", cluster=\"{{cluster}}\"}"
    },
    {
     "expr": "sum(cilium_controllers_failing{k8s_app=\"cilium\", pod=~\"$pod\"}) by(pod, cluster)",
     "legendFormat": "Failed {pod=\"{{pod}}\", cluster=\"{{cluster}}\"}"
    }
   ]
  },
  {
   "title": "Controller Durations",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 156 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(cilium_controllers_runs_duration_seconds_sum{k8s_app=\"cilium\", pod=~\"$pod\"}[1m])) by (pod, status, cluster) / sum(rate(cilium_controllers_runs_duration_seconds_count{k8s_app=\"cilium\", pod=~\"$pod\"}[1m])) by (pod, status, cluster)",
     "legendFormat": "{{status}} {pod=\"{{pod}}\", cluster=\"{{cluster}}\"}"
    }
   ]
  },
  { "title": "Kubernetes integration", "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 161 } },
  {
   "title": "Valid, Unnecessary K8s Events Received",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 162 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(cilium_kubernetes_events_received_total{k8s_app=\"cilium\", equal=\"true\", valid=\"true\", pod=~\"$pod\"}[5m])) by (pod, scope, action, cluster)",
     "legendFormat": "{{action}} {{scope}} {pod=\"{{pod}}\", cluster=\"{{cluster}}\"}"
    }
   ]
  },
  {
   "title": "Invalid, Unnecessary K8s Events Received",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 162 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(cilium_kubernetes_events_received_total{k8s_app=\"cilium\", equal=\"true\", valid=\"false\", pod=~\"$pod\"}[5m])) by (pod, scope, action, cluster)",
     "legendFormat": "{{action}} {{scope}} {pod=\"{{pod}}\", cluster=\"{{cluster}}\"}"
    }
   ]
  },
  {
   "title": "Valid, Necessary K8s Events Received",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 168 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(cilium_kubernetes_events_received_total{k8s_app=\"cilium\", equal=\"false\", valid=\"true\", pod=~\"$pod\"}[5m])) by (pod, scope, action, valid, cluster)",
     "legendFormat": "{{action}} {{scope}} {pod=\"{{pod}}\", cluster=\"{{cluster}}\"}"
    }
   ]
  },
  {
   "title": "Invalid, Necessary K8s Events Received",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 168 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(cilium_kubernetes_events_received_total{k8s_app=\"cilium\", equal=\"false\", valid=\"false\", pod=~\"$pod\"}[5m])) by (pod, scope, action)",
     "legendFormat": "{{action}} {{scope}}"
    }
   ]
  },
  {
   "title": "CiliumNetworkPolicy Events",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 176 },
   "yaxes": [
    { "format": "opm" }
   ],
   "targets": [
    {
     "expr": "avg(rate(cilium_kubernetes_events_total{k8s_app=\"cilium\", scope=\"CiliumNetworkPolicy\", pod=~\"$pod\"}[1m])) by (pod, action) * 60",
     "legendFormat": "{{action}} avg"
    }
   ]
  },
  {
   "title": "NetworkPolicy Events",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 176 },
   "yaxes": [
    { "format": "opm" }
   ],
   "targets": [
    {
     "expr": "avg(rate(cilium_kubernetes_events_total{k8s_app=\"cilium\", scope=\"NetworkPolicy\", pod=~\"$pod\"}[1m])) by (pod, action) * 60",
     "legendFormat": "{{action}} avg"
    }
   ]
  },
  {
   "title": "Pod Events",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 183 },
   "yaxes": [
    { "format": "opm" }
   ],
   "targets": [
    {
     "expr": "avg(rate(cilium_kubernetes_events_total{k8s_app=\"cilium\", scope=\"Pod\", pod=~\"$pod\"}[1m])) by (pod, action) * 60",
     "legendFormat": "{{action}} avg"
    }
   ]
  },
  {
   "title": "Node Events",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 183 },
   "yaxes": [
    { "format": "opm" }
   ],
   "targets": [
    {
     "expr": "avg(rate(cilium_kubernetes_events_total{k8s_app=\"cilium\", scope=\"Node\", pod=~\"$pod\"}[1m])) by (pod, action) * 60",
     "legendFormat": "{{action}} avg"
    }
   ]
  },
  {
   "title": "Service Events",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 190 },
   "yaxes": [
    { "format": "opm" }
   ],
   "targets": [
    {
     "expr": "avg(rate(cilium_kubernetes_events_total{k8s_app=\"cilium\", scope=\"Service\", pod=~\"$pod\"}[1m])) by (pod, action) * 60",
     "legendFormat": "{{action}}"
    }
   ]
  },
  {
   "title": "Endpoints Events",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 190 },
   "yaxes": [
    { "format": "opm" }
   ],
   "targets": [
    {
     "expr": "avg(rate(cilium_kubernetes_events_total{k8s_app=\"cilium\", scope=\"Endpoint\", pod=~\"$pod\"}[1m])) by (pod, action) * 60",
     "legendFormat": "{{action}}"
    }
   ]
  },
  {
   "title": "Namespace Events",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 197 },
   "yaxes": [
    { "format": "opm" }
   ],
   "targets": [
    {
     "expr": "avg(rate(cilium_kubernetes_events_total{k8s_app=\"cilium\", scope=\"Namespace\", pod=~\"$pod\"}[1m])) by (pod, action) * 60",
     "legendFormat": "{{action}}"
    }
   ]
  }
 ]
}