name: intel-i915

image:
  hub: intel
  tag: ""

initImage:
  enable: false
  hub: intel
  tag: ""

sharedDevNum: 1
logLevel: 2
resourceManager: false
enableMonitoring: true
allocationPolicy: "none"

nodeSelector:
  gpu: i915

tolerations:

nodeFeatureRule: false 
