roles: "kube,app"
proxyAddr: "carson.teleport.sh:443"
enterprise: true
joinParams:
  method: "iam"
  tokenName: "iam-token"
kubeClusterName: "homelab"
highAvailability:
  replicaCount: 2
  podDisruptionBudget:
    enabled: true
    minAvailable: 1
podMonitor:
  enabled: true
  additionalLabels:
    release: kps
apps:
- name: grafana
  uri: http://kps-grafana.monitoring.svc.cluster.local.:80
  labels:
    env: homelab
    category: monitoring
- name: prometheus
  uri: http://kps-prometheus.monitoring.svc.cluster.local.:9090
  labels:
    env: homelab
    category: monitoring
- name: alertmanager
  uri: http://kps-alertmanager.monitoring.svc.cluster.local.:9093
  labels:
    env: homelab
    category: monitoring
- name: argocd
  uri: http://argocd-server.argocd.svc.cluster.local.:443
  labels:
    env: homelab
    category: cd
- name: longhorn
  uri: http://longhorn-frontend.longhorn-system.svc.cluster.local.:80
  labels:
    env: homelab
    category: storage

clusterDomain: "cluster.local"
updater:
  enabled: false
podSecurityPolicy:
  enabled: false
log:
  format: json
extraEnv:
- name: AWS_REGION
  value: us-west-2
- name: AWS_CONTAINER_CREDENTIALS_FULL_URI
  value: http://169.254.170.23:8080/v1/container-credentials
- name: AWS_CONTAINER_AUTHORIZATION_TOKEN_FILE
  value: /var/run/secrets/kubernetes.io/serviceaccount/token
