githubConfigUrl: https://github.com/rcanderson23/homelab-aws-creds
githubConfigSecret: gha-runners-config
minRunners: 1
maxRunners: 3
containerMode:
  type: kubernetes
  kubernetesModeWorkVolumeClaim:
    accessModes: ["ReadWriteOnce"]
    storageClassName: openebs-hostpath
    resources:
      requests:
        storage: 25Gi
template:
  spec:
    containers:
      - name: runner
        image: ghcr.io/actions/actions-runner:latest
        command: ["/home/runner/run.sh"]
        env:
          - name: ACTIONS_RUNNER_REQUIRE_JOB_CONTAINER
            value: "false"
controllerServiceAccount:
  name: actions-runner-system-gha-rs-controller
  namespace: actions-runner-system
