githubConfigUrl: https://github.com/rcanderson23/homelab-aws-creds
githubConfigSecret: gha-runners-config
minRunners: 1
maxRunners: 3
containerMode:
  type: dind
  #kubernetesModeWorkVolumeClaim:
  #  accessModes: ["ReadWriteOnce"]
  #  storageClassName: openebs-hostpath
  #  resources:
  #    requests:
  #      storage: 25Gi
#template:
#  spec:
#    containers:
#      - name: runner
#        image: ghcr.io/actions/actions-runner:latest
#        command: ["/home/runner/run.sh"]
#        env:
#          - name: ACTIONS_RUNNER_REQUIRE_JOB_CONTAINER
#            value: "false
template:
  spec:
    #initContainers:
    #- name: init-dind-externals
    #  image: ghcr.io/actions/actions-runner:latest
    #  command: ["cp", "-r", "-v", "/home/runner/externals/.", "/home/runner/tmpDir/"]
    #  volumeMounts:
    #    - name: dind-externals
    #      mountPath: /home/runner/tmpDir
    containers:
    - name: runner
      image: ghcr.io/actions/actions-runner:latest
      command: ["/home/runner/run.sh"]
      env:
          #    - name: DOCKER_HOST
          #      value: unix:///var/run/docker.sock
        - name: ACTIONS_RUNNER_REQUIRE_JOB_CONTAINER
          value: "false"
        #  volumeMounts:
        #    - name: work
        #      mountPath: /home/runner/_work
        #    - name: dind-sock
        #      mountPath: /var/run
        #- name: dind
        #  image: docker:dind
        #  args:
        #    - dockerd
        #    - --host=unix:///var/run/docker.sock
        #    - --group=$(DOCKER_GROUP_GID)
        #  env:
        #    - name: DOCKER_GROUP_GID
        #      value: "123"
        #  securityContext:
        #    privileged: true
        #  volumeMounts:
        #    - name: work
        #      mountPath: /home/runner/_work
        #    - name: dind-sock
        #      mountPath: /var/run
        #    - name: dind-externals
        #      mountPath: /home/runner/externals
        #volumes:
        #- name: work
        #  emptyDir: {}
        #- name: dind-sock
        #  emptyDir: {}
        #- name: dind-externals
        #  emptyDir: {}
controllerServiceAccount:
  name: actions-runner-system-gha-rs-controller
  namespace: actions-runner-system
