githubConfigUrl: https://github.com/rcanderson23/homelab-aws-creds
githubConfigSecret: gha-runners-config
minRunners: 0
maxRunners: 3
containerMode:
  type: dind
template:
  spec:
    affinity:
      podAntiAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                  - key: app.kubernetes.io/name
                    operator: In
                    values:
                      - homelab-aws-creds-runners
              topologyKey: "kubernetes.io/hostname"
    containers:
    - name: runner
      image: ghcr.io/actions/actions-runner:latest
      command: ["/home/runner/run.sh"]
      env:
        - name: ACTIONS_RUNNER_REQUIRE_JOB_CONTAINER
          value: "false"
      resources:
        limits:
          cpu: 12
    - name: dind
      image: docker:dind
      resources:
        limits:
          cpu: 12
controllerServiceAccount:
  name: actions-runner-system-gha-rs-controller
  namespace: actions-runner-system
