apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cilium
  namespace: argocd
spec:
  sources:
  - repoURL: 'https://helm.cilium.io'
    chart: cilium
    targetRevision: 1.17.6
    helm:
      valueFiles:
      - $values/argocd/apps/core/cilium/values.yaml
  - repoURL: 'https://github.com/rcanderson23/homelab2.git'
    targetRevision: main
    ref: values
  - repoURL: 'https://github.com/rcanderson23/homelab2.git'
    path: 'argocd/apps/core/cilium/manifests'
    targetRevision: main
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
