serviceMonitor:
  enabled: true
  additionalLabels:
    release: kps

triggerLoopOnEvent: true
env:
- name: AWS_REGION
  value: us-west-2
- name: AWS_CONTAINER_CREDENTIALS_FULL_URI
  value: http://169.254.170.23:8080/v1/container-credentials
- name: AWS_CONTAINER_AUTHORIZATION_TOKEN_FILE
  value: /var/run/secrets/kubernetes.io/serviceaccount/token

# -- _Kubernetes_ resources to monitor for DNS entries.
sources:
  - service
  - ingress
  - gateway-httproute
  - gateway-tlsroute
  - gateway-tcproute
  - gateway-udproute
