serviceMonitor:
  enabled: true
  additionalLabels:
    release: kps

triggerLoopOnEvent: true
labelFilter: "dns.homelabtech.net/provider=externaldns"
# -- _Kubernetes_ resources to monitor for DNS entries.
sources:
  - service
  - ingress
  - gateway-httproute
  - gateway-tlsroute
  - gateway-tcproute
  - gateway-udproute
