metrics:
  controllerManagerAddr: ":8080"
  listenerAddr: ":8080"
  listenerEndpoint: "/metrics"

flags:
  logLevel: "debug"
  logFormat: "json"
  runnerMaxConcurrentReconciles: 2
  updateStrategy: "immediate"
  excludeLabelPropagationPrefixes:
    - "argocd.argoproj.io/instance"
