---
apiVersion: deviceplugin.intel.com/v1
kind: GpuDevicePlugin
metadata:
  name: i915
spec:
  enableMonitoring: true
  image: intel/intel-gpu-plugin:0.37.1@sha256:004641b2547d58f1eadce58473fa160ad71377de1eb588cf1f82832387bf3e33
  logLevel: 2
  nodeSelector:
    gpu: i915
  preferredAllocationPolicy: none
  sharedDevNum: 1
