---
apiVersion: deviceplugin.intel.com/v1
kind: GpuDevicePlugin
metadata:
  name: i915
spec:
  enableMonitoring: true
  image: intel/intel-gpu-plugin:0.37.0@sha256:7001200071db10587fc31184eedda4f5cf291efba737adf85a8c80539f7fa5e1
  logLevel: 2
  nodeSelector:
    gpu: i915
  preferredAllocationPolicy: none
  sharedDevNum: 1
