apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: envoy-gateway
  namespace: argocd
spec:
  sources:
  - repoURL: docker.io
    chart: envoyproxy/gateway-helm
    targetRevision: 1.2.4
    helm:
      valueFiles:
      - $values/argocd/apps/core/envoy-gateway/values.yaml
  - repoURL: 'https://github.com/rcanderson23/homelab2.git'
    targetRevision: main
    ref: values
  - repoURL: 'https://github.com/rcanderson23/homelab2.git'
    path: 'argocd/apps/core/envoy-gateway/manifests'
    targetRevision: main
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
  destination:
    server: https://kubernetes.default.svc
    namespace: envoy-gateway
