serviceMonitor:
  enabled: true
  labels:
    release: kps
route:
  main:
    enabled: true
    apiVersion: gateway.networking.k8s.io/v1
    kind: HTTPRoute
    hostnames:
      - grafana.carsonanderson.net
    parentRefs:
      - name: private-gateway
        namespace: envoy-gateway
    matches:
      - path:
          type: PathPrefix
          value: /
persistence:
  enabled: false
datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
    - name: Prometheus
      type: prometheus
      uid: prometheus
      url: http://kps-prometheus.monitoring.svc.cluster.local.:9090
      access: proxy
      isDefault: true
    - name: Alertmanager
      type: alertmanager
      uid: alertmanager
      url: http://kps-alertmanager.monitoring.svc.cluster.local.:9093
      access: proxy
    - name: Loki
      type: loki
      uid: loki
      url: http://loki-headless.loki.svc.cluster.local.:3100
      access: proxy
dashboardProviders:
  dashboardproviders.yaml:
    apiVersion: 1
    providers:
    - name: 'default'
      orgId: 1
      folder: ''
      type: file
      disableDeletion: false
      editable: true
      options:
        path: /var/lib/grafana/dashboards/default
dashboards:
  default:
    cert-manager:
      gnetId: 20842
      revision: 3
      datasource: Prometheus
    external-dns:
      # renovate: depName="External-dns"
      gnetId: 15038
      revision: 3
      datasource: Prometheus
    external-secrets:
      url: https://raw.githubusercontent.com/external-secrets/external-secrets/main/docs/snippets/dashboard.json
      datasource: Prometheus
    kubernetes-api-server:
      gnetId: 15761
      revision: 18
      datasource: Prometheus
    kubernetes-coredns:
      gnetId: 15762
      revision: 19
      datasource: Prometheus
    kubernetes-global:
      gnetId: 15757
      revision: 42
      datasource: Prometheus
    kubernetes-namespaces:
      gnetId: 15758
      revision: 41
      datasource: Prometheus
    kubernetes-nodes:
      gnetId: 15759
      revision: 32
      datasource: Prometheus
    kubernetes-pods:
      gnetId: 15760
      revision: 34
      datasource: Prometheus
    kubernetes-volumes:
      gnetId: 11454
      revision: 14
      datasource: Prometheus
    node-exporter-full:
      gnetId: 1860
      revision: 37
      datasource: Prometheus
    prometheus:
      gnetId: 19105
      revision: 6
      datasource: Prometheus
    smartctl-exporter:
      gnetId: 22604
      revision: 2
      datasource:
        - { name: DS_PROMETHEUS, value: Prometheus }
plugins:
  - grafana-clock-panel
  - grafana-piechart-panel
  - grafana-worldmap-panel
grafana.ini:
  paths:
    data: /var/lib/grafana/
    logs: /var/log/grafana
    plugins: /var/lib/grafana/plugins
    provisioning: /etc/grafana/provisioning
  analytics:
    check_for_updates: false
    reporting_enabled: false
  log:
    mode: console
  log.console:
    format: json
  grafana_net:
    url: https://grafana.net
  auth.anonymous:
    enabled: true
    org_role: Admin
  live:
    allowed_orgins: "https://grafana.carsonanderson.net,https://grafana.carson.teleport.sh"
