fullnameOverride: "kps"
defaultRules:
  create: true
  rules:
    kubeProxy: false

alertmanager:
  enabled: true
  alertmanagerConfiguration:
    name: alertmanager
  podDisruptionBudget:
    enabled: false
    minAvailable: 1
  alertmanagerSpec:
    storage:
      volumeClaimTemplate:
        spec:
          storageClassName: longhorn
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 10Gi

grafana:
  enabled: false
  forceDeployDashboards: true
kubeApiServer:
  enabled: true
kubelet:
  enabled: true
kubeControllerManager:
  enabled: true
coreDns:
  enabled: true
kubeEtcd:
  enabled: true
  endpoints:
  - 10.192.1.4

kubeScheduler:
  enabled: true
kubeProxy:
  enabled: false
kubeStateMetrics:
  enabled: true
nodeExporter:
  enabled: true
prometheus:
  enabled: true
  prometheusSpec:
    retention: 30d
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: longhorn
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 60Gi
