apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root
  namespace: argocd
spec:
  sources:
  - repoURL: 'https://github.com/rcanderson23/homelab2.git'
    targetRevision: main
    path: argocd/apps
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
