githubConfigUrl: https://github.com/rcanderson23/mesh-cni
githubConfigSecret: gha-runners-config
minRunners: 1
maxRunners: 3
controllerServiceAccount:
  namespace: arc-system
  name: actions-runner-system-gha-rs-controller
# use full template otherwise unable to specify resources on dind
template:
  spec:
    affinity:
      podAntiAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                  - key: app.kubernetes.io/name
                    operator: In
                    values:
                      - mesh-cni-runners
              topologyKey: "kubernetes.io/hostname"
    initContainers:
    - name: init-dind-externals
      image: ghcr.io/actions/actions-runner:latest
      command: ["cp", "-r", "/home/runner/externals/.", "/home/runner/tmpDir/"]
      volumeMounts:
        - name: dind-externals
          mountPath: /home/runner/tmpDir
    - name: dind
      image: docker:dind
      args:
        - dockerd
        - --host=unix:///var/run/docker.sock
        - --group=$(DOCKER_GROUP_GID)
      env:
        - name: DOCKER_GROUP_GID
          value: "123"
      securityContext:
        privileged: true
      restartPolicy: Always
      startupProbe:
        exec:
          command:
            - docker
            - info
        initialDelaySeconds: 0
        failureThreshold: 24
        periodSeconds: 5
      volumeMounts:
        - name: work
          mountPath: /home/runner/_work
        - name: dind-sock
          mountPath: /var/run
        - name: dind-externals
          mountPath: /home/runner/externals
        - name: dind-config
          mountPath: /etc/docker
    containers:
    - name: runner
      image: ghcr.io/actions/actions-runner:latest
      command:
      - /bin/sh
      - -c
      - |
        # Wait for Docker to be ready before starting runner
        echo "Waiting for docker..."
        until docker info >/dev/null 2>&1; do sleep 5; done
        /home/runner/run.sh
      env:
        - name: DOCKER_HOST
          value: unix:///var/run/docker.sock
        - name: RUNNER_WAIT_FOR_DOCKER_IN_SECONDS
          value: "120"
      volumeMounts:
        - name: work
          mountPath: /home/runner/_work
        - name: dind-sock
          mountPath: /var/run
    volumes:
    - name: work
      emptyDir: {}
    - name: dind-sock
      emptyDir: {}
    - name: dind-externals
      emptyDir: {}
    - name: dind-config
      configMap:
        name: dind-config
