---
apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: alertmanager
spec:
  route:
    groupInterval: 10m
    groupBy: ["alertname"]
    groupWait: 1m
    receiver: pushover
    repeatInterval: 12h
    routes:
      - receiver: "null"
        matchers:
          - name: alertname
            value: InfoInhibitor
            matchType: =
      - receiver: pushover
        matchers:
          - name: severity
            value: critical
            matchType: =
  inhibitRules:
    - equal:
        - namespace
        - alertname
      sourceMatch:
        - name: severity 
          value: critical
          matchType: =
      targetMatch:
        - name: severity 
          value: warning|info
          matchType: =~
    - equal:
        - namespace
        - alertname
      sourceMatch:
        - name: severity
          value: warning
          matchType: =
      targetMatch:
        - name: severity
          value: info
          matchType: =
    - equal:
        - namespace
      sourceMatch:
        - name: alertname
          value: InfoInhibitor
          matchType: =
      targetMatch:
        - name: severity
          value: info
          matchType: =
    - targetMatch:
        - name: alertname
          value: InfoInhibitor
          matchType: =
  receivers:
    - name: "null"
    - name: pushover
      pushoverConfigs:
        - html: true
          message: |-
            {{- range .Alerts }}
              {{- if ne .Annotations.description "" }}
                {{ .Annotations.description }}
              {{- else if ne .Annotations.summary "" }}
                {{ .Annotations.summary }}
              {{- else if ne .Annotations.message "" }}
                {{ .Annotations.message }}
              {{- else }}
                Alert description not available
              {{- end }}
              {{- if gt (len .Labels.SortedPairs) 0 }}
                <small>
                  {{- range .Labels.SortedPairs }}
                    <b>{{ .Name }}:</b> {{ .Value }}
                  {{- end }}
                </small>
              {{- end }}
            {{- end }}
          priority: |-
            {{ if eq .Status "firing" }}1{{ else }}0{{ end }}
          sendResolved: true
          title: >-
            [{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}]
            {{ .CommonLabels.alertname }}
          ttl: 86400s
          token:
            name: pushover
            key: token
          userKey:
            name: pushover
            key: user_key
          urlTitle: View in Alertmanager
