apiVersion: "cilium.io/v2"
kind: CiliumLocalRedirectPolicy
metadata:
  name: "aws-creds"
spec:
  redirectFrontend:
    addressMatcher:
      ip: "169.254.170.23"
      toPorts:
      - port: "8080"
        protocol: TCP
  redirectBackend:
    localEndpointSelector:
      matchLabels:
        app.kubernetes.io/name: homelab-aws-creds
    toPorts:
      - port: "8080"
        protocol: TCP
