apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cilium
  namespace: argocd
spec:
  sources:
  - repoURL: 'https://helm.cilium.io'
    chart: cilium
    targetRevision: 1.15.6
    helm:
      valueFiles:
          - $values/argocd/values/cilium.yaml
  - repoURL: 'https://github.com/rcanderson23/homelab2.git'
    targetRevision: main
    ref: values
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
