apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: sabnzbd
spec:
  data:
  - remoteRef:
      key: ad7582df-8ece-47cf-a0ef-b269000ccf5d
    secretKey: SABNZBD__API_KEY
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secretsmanager
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
status:
  binding:
    name: sabnzbd
  conditions:
  - lastTransitionTime: "2025-01-18T02:18:04Z"
    message: secret synced
    reason: SecretSynced
    status: "True"
    type: Ready
  refreshTime: "2025-01-19T04:18:03Z"
  syncedResourceVersion: 1-d0bc31fc4f877a0ba81257f41a7007b6
