apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: argocd
spec:
  sources:
  - repoURL: https://charts.external-secrets.io
    chart: external-secrets
    targetRevision: 0.12.1
    helm:
      valuesObject:
        bitwarden-sdk-server:
          enabled: true
        leaderElection: true
        serviceMonitor:
          enabled: false
#      valueFiles:
#          - $values/argocd/values/external-secrets.yaml
#  - repoURL: 'https://github.com/rcanderson23/homelab2.git'
#    targetRevision: main
#    ref: values
  project: default
  syncPolicy:
    automated:
      #prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
  destination:
    server: https://kubernetes.default.svc
    namespace: external-secrets
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: external-secrets-ca
  namespace: external-secrets
spec:
  isCA: true
  commonName: external-secrets
  secretName: external-secrets-root-secret
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: selfsigned-cluster-issuer
    kind: ClusterIssuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: external-secrets-issuer
  namespace: external-secrets
spec:
  ca:
    secretName: external-secrets-root-secret
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: bitwarden-tls
  namespace: external-secrets
spec:
  isCA: false
  commonName: bitwarden-sdk-server
  secretName: bitwarden-tls-certs
  usages:
  - server auth
  dnsNames:
  - bitwarden-sdk-server.external-secrets.svc.cluster.local
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: external-secrets-issuer
    kind: Issuer
    group: cert-manager.io
---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: bitwarden-secretsmanager
spec:
  provider:
    bitwardensecretsmanager:
      auth:
        secretRef:
          credentials:
            key: token
            name: bitwarden-access-token
            namespace: external-secrets
      bitwardenServerSDKURL: https://bitwarden-sdk-server.external-secrets.svc.cluster.local:9998
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJlRENDQVIyZ0F3SUJBZ0lSQUp4WGhIa2hmVHVSc2xUcVozM0gvTFF3Q2dZSUtvWkl6ajBFQXdJd0d6RVoKTUJjR0ExVUVBeE1RWlhoMFpYSnVZV3d0YzJWamNtVjBjekFlRncweU5UQXhNVEl3TlRRNU5EaGFGdzB5TlRBMApNVEl3TlRRNU5EaGFNQnN4R1RBWEJnTlZCQU1URUdWNGRHVnlibUZzTFhObFkzSmxkSE13V1RBVEJnY3Foa2pPClBRSUJCZ2dxaGtqT1BRTUJCd05DQUFUNWMzanh6RjQ3a3BWN2VZdmFSQmtCYzBhd3p1Qy9NenNkRjFoN0I3RWUKQ0EranAyNTNCeTh5RkkxaUlmWEFCUlFBU29reXkxclVKYXVoRi9Xand0NStvMEl3UURBT0JnTlZIUThCQWY4RQpCQU1DQXFRd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBZEJnTlZIUTRFRmdRVW9udnkwelI5RzZOelNXcU4ydHh1CmptYUZuS0l3Q2dZSUtvWkl6ajBFQXdJRFNRQXdSZ0loQUtsa0ZFLytPK2xWUnRFOVBobDhLckMxNXh5ZmZPOGkKZEtibFc4NjgwZVFDQWlFQWk3VG9YdDlwWXFVRjhtNzVsNVE0cHJIQTZkdHFzTWRsWnlHQTJxaHlXNm89Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
      organizationID: 8f6f4b55-6743-4f39-87d1-b2570045934f
      projectID: 548ad524-ad16-4399-a746-b25700465377
