---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns
  namespace: argocd
spec:
  destination:
    namespace: external-dns
    server: https://kubernetes.default.svc
  project: default
  sources:
  - chart: external-dns
    helm:
      valueFiles:
      - $values/argocd/values/external-dns.yaml
  - repoURL: 'https://github.com/rcanderson23/homelab2.git'
    targetRevision: main
    ref: values
    repoURL: https://kubernetes-sigs.github.io/external-dns/
    targetRevision: 1.15.0
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
