---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metrics-server
  namespace: argocd
spec:
  destination:
    namespace: metrics-server
    server: https://kubernetes.default.svc
  project: default
  sources:
  - chart: metrics-server
    helm:
      valueFiles:
      - $values/argocd/apps/core/metrics-server/values.yaml
    repoURL: https://kubernetes-sigs.github.io/metrics-server/
    targetRevision: 3.12.2
  - repoURL: 'https://github.com/rcanderson23/homelab2.git'
    targetRevision: main
    ref: values
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
