---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: credentials
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secretsmanager
  data:
  - remoteRef:
      key: 7d710f5a-2878-4be6-894a-b276015e2925
    secretKey: key
  - remoteRef:
      key: 4ead66fd-f0c5-40ed-8696-b276015e66d6
    secretKey: key-id
