---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
spec:
  destination:
    namespace: cert-manager
    server: https://kubernetes.default.svc
  project: default
  sources:
  - chart: cert-manager
    helm:
      valueFiles:
      - $values/argocd/apps/core/cert-manager/values.yaml
    repoURL: https://charts.jetstack.io
    targetRevision: 1.18.2
  - repoURL: 'https://github.com/rcanderson23/homelab2.git'
    targetRevision: main
    ref: values
  - repoURL: 'https://github.com/rcanderson23/homelab2.git'
    path: 'argocd/apps/core/cert-manager/manifests'
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
