config:
  apiVersion: controller.config.cert-manager.io/v1alpha1
  kind: ControllerConfiguration
  enableGatewayAPI: true
crds:
  enabled: true
enableCertificateOwnerRef: true
global:
  leaderElection:
    namespace: cert-manager
prometheus:
  enabled: true
  servicemonitor:
    enabled: true
