---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sonarr
  namespace: argocd
spec:
  sources:
  - repoURL: ghcr.io
    chart: bjw-s/helm/app-template
    targetRevision: 3.6.1
    helm:
      valueFiles:
      - $values/argocd/apps/media/sonarr/values.yaml
  - repoURL: 'https://github.com/rcanderson23/homelab2.git'
    targetRevision: main
    ref: values
  - repoURL: 'https://github.com/rcanderson23/homelab2.git'
    path: 'argocd/apps/media/sonarr/manifests'
    targetRevision: main
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
  destination:
    namespace: media
    server: https://kubernetes.default.svc
